services:
    webserver_user:
        container_name: hrm_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
            args:
                PHP_FPM_SERVER: hrm_api
                PHP_FPM_PORT: 9000
        ports:
            - '${DOCKER_NGINX_PORT-8000}:80'
        volumes:
            - './public:/var/www/html/public'
            - './storage:/var/www/html/storage'
        networks:
            - backend
        depends_on:
            - app_user

    app_user:
        container_name: hrm_api
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - '.:/var/www/html'
            - './docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
        networks:
            - backend
        depends_on:
            - mysql

    mysql:
        #    platform: linux/x86_64 # for Mac M1
        container_name: hrm_mysql
        image: 'mysql:8.0.32'
        ports:
            - '${DOCKER_MYSQL_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-data:/var/lib/mysql'
        networks:
            - backend

networks:
    backend:
        name: hrm_network

volumes:
    mysql-data:
        driver: local
